### PR TITLE
Fix missing nuke regions / principal budget amount

### LINKED ISSUE #214: Unable to create lease: "has already spent $0.00 of their budget"
**Version information**

DCE v0.24.1

**Describe the bug**

Unable to create a lease for the same principal a second time:

```
$ dce leases create -p myuser -b 100 -c USD -e noreply@example.com
> Lease created: { "accountId": 123, ... }
$ dce leases end -a 123 -p myuser
$ dce leases create -p myuser -b 100 -c USD -e noreply@example.com
> [POST /leases][400] postLeasesBadRequest 
```
Showing with dce-cli for clarify, but I'm able to reproduce this hitting the API directly.
Here's the actual 400 response in postman:

Screenshot_2020-01-10 12 23 52_oPJWu8

I verified that my `leases` lambda is configured with the correct values:
image
...so I would guess this is something in the code (not in my TF configuration)

**To Reproduce**

See above

**Expected behavior**

I should be able to create a new lease for the same principal, unless that principal has actually exceeded the usage limit

**Additional context**

This is new bug introduced since v0.23.0 (our last working deployment)

### LINKED ISSUE #221: Nuke template not rendering regions, only nuking global resources
**Version information**

DCE v0.24.1

**Describe the bug**

Nuke is not rendering the `var.allowedRegions` into the template file. Result is that nuke is only working on global resources (eg. IAM), and skipping most of the other resources in the account

### LINKED ISSUE #224: Principal missing `execute-api:Invoke` permissions
**Version information**

v0.24.1

**Describe the bug**

DCEPrincipal role is missing the `execute-api:Invoke` permissions.
Besides this being something DCE users should have access to, it's also blocking some of our "DCE inside DCE" work 
(see #206 ),  because our DCE principal can't run functional tests

### PR DESCRIPTION
**Pull request by eschwartz**
## Proposed changes

We had some configurations that weren't completely wired into our system.

Fixes #214 
Fixes #221 

**EDIT** Added DCE Principal policy change to allow `execute-api:Invoke` (fixes #224 ). This was blocking me from running functional tests locally, and it's a quick fix.

**EDIT** Changed default `allowed_regions` to just `us-east-1`. I was testing out nuke, and my codebuilt took >1hr to complete with the default 18 regions. I don't think that's good default behavior.

image

I've tested this out in our nonprod environment, to verify that:
- Nuke runs successfully, and targets the requested resources
- I can create a another lease for the same principal, even after accumulating spend in the Usage db
- I get a 400 if I try to create a lease, when my principal is over budget for the week

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have filled out this PR template
- [x] I have read the [CONTRIBUTING](https://github.com/Optum/dce/blob/master/docs/CONTRIBUTING.md) doc
- [x] I have added automated tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (`README.md`, inline comments, etc.)
- [x] I have updated the `CHANGELOG.md` under a `## next` release, with a short summary of my changes

### CODE REVIEW

File: cmd/codebuild/reset/main.go [hunk 1]
```diff
@@ -221,7 +221,7 @@ func generateNukeConfig(svc *service, f io.Writer) error {
 		AdminRole:       config.accountAdminRoleName,
 		PrincipalRole:   config.accountPrincipalRoleName,
 		PrincipalPolicy: config.accountPrincipalPolicyName,
-		Regions:         config.allowedRegions,
+		Regions:         config.nukeRegions,
```
Comment (eschwartz) [inline cmd/codebuild/reset/main.go]: Renamed to `nukeRegions` (it's not regions we're allowing, it the regions we're nuking)

File: cmd/lambda/leases/create.go [hunk 2]
```diff
@@ -29,10 +28,11 @@ type createLeaseRequest struct {
 func CreateLease(w http.ResponseWriter, r *http.Request) {
 
 	c := leaseValidationContext{
-		maxLeaseBudgetAmount:     aws.Float64Value(maxLeaseBudgetAmount),
```
Comment (eschwartz) [inline cmd/lambda/leases/create.go]: no need to use the aws pkg to dereference pointer, can just use built-in golang syntax.

File: cmd/lambda/leases/create.go [hunk 3]
```diff
@@ -29,10 +28,11 @@ type createLeaseRequest struct {
...
-		maxLeasePeriod:           aws.Int64Value(maxLeasePeriod),
-		defaultLeaseLengthInDays: aws.IntValue(defaultLeaseLengthInDays),
-		principalBudgetPeriod:    aws.StringValue(principalBudgetPeriod),
+		maxLeaseBudgetAmount:     *maxLeaseBudgetAmount,
+		maxLeasePeriod:           *maxLeasePeriod,
+		defaultLeaseLengthInDays: *defaultLeaseLengthInDays,
+		principalBudgetPeriod:    *principalBudgetPeriod,
+		principalBudgetAmount:    *principalBudgetAmount,
```
Comment (eschwartz) [inline cmd/lambda/leases/create.go]: this `principalBudgetAmount` param was missing

File: cmd/codebuild/reset/service.go [hunk 4]
```diff
@@ -62,6 +62,7 @@ func (svc *service) config() *serviceConfig {
 		nukeTemplateDefault: common.RequireEnv("RESET_NUKE_TEMPLATE_DEFAULT"),
 		nukeTemplateBucket:  common.RequireEnv("RESET_NUKE_TEMPLATE_BUCKET"),
 		nukeTemplateKey:     common.RequireEnv("RESET_NUKE_TEMPLATE_KEY"),
+		nukeRegions:         common.RequireEnvStringSlice("RESET_NUKE_REGIONS", ","),
```
Comment (eschwartz) [inline cmd/codebuild/reset/service.go]: was missing this env var

File: modules/reset_codebuild.tf [hunk 5]
```diff
@@ -108,14 +108,8 @@ resource "aws_codebuild_project" "reset_build" {
...
-      name  = "RESET_NAMESPACE"
-      value = var.namespace
-      type  = "PLAINTEXT"
-    }
-
-    environment_variable {
-      name  = "IS_PR"
-      value = local.isPr ? "true" : "false"
+      name  = "RESET_NUKE_REGIONS"
+      value = join("," var.allowed_regions)
```
Comment (eschwartz) [inline modules/reset_codebuild.tf]: We nuke all the regions which the principal is allowed access to.

File: modules/reset_codebuild.tf [hunk 6]
```diff
@@ -108,14 +108,8 @@ resource "aws_codebuild_project" "reset_build" {
     }
 
     environment_variable {
-      name  = "RESET_NAMESPACE"
```
Comment (eschwartz) [inline modules/reset_codebuild.tf]: `RESET_NAMESPACE` and `IS_PR` env vars aren't being used anywhere (did a full code search to double-check)

File: cmd/lambda/leases/validate.go [hunk 7]
```diff
@@ -78,7 +78,10 @@ func validateLeaseFromRequest(context *leaseValidationContext, req *http.Request
 	}
 
 	if spent > context.principalBudgetAmount {
-		validationErrStr := fmt.Sprintf("Unable to create lease: User principal %s has already spent %f of their principal budget", requestBody.PrincipalID, math.Round(context.principalBudgetAmount))
+		validationErrStr := fmt.Sprintf(
```
Comment (eschwartz) [inline cmd/lambda/leases/validate.go]: The test for this error messages was failing. Figured I'll clean up the message while I'm in here
(rounds to 2 decimal places, includes actual spend)

File: tests/acceptance/api_test.go [hunk 8]
```diff
@@ -1766,9 +1766,12 @@ func TestApi(t *testing.T) {
 			// Verify error response json
 			// Get nested json in response json
 			err := data["error"].(map[string]interface{})
-			errStr := fmt.Sprintf("Unable to create lease: User principal %s has already spent 0.000000 of their principal budget", principalID)
 			require.Equal(t, "RequestValidationError", err["code"].(string))
-			require.Equal(t, errStr, err["message"].(string))
+			require.Equal(t,
```
Comment (eschwartz) [inline tests/acceptance/api_test.go]: This test was expecting buggy behavior (that budget=0). That buggy behavior was fixed in the PR, so test is updated.
Also, cleaned up the error response message

File: tests/acceptance/api_test.go [hunk 9]
```diff
@@ -2071,6 +2074,7 @@ func parseResponseArrayJSON(t *testing.T, resp *apiResponse) []map[string]interf
 	// Go doesn't allow you to cast directly to []map[string]interface{}
 	// so we need to mess around here a bit.
 	// This might be relevant: https://stackoverflow.com/questions/38579485/golang-convert-slices-into-map
+	require.IsTypef(t, []interface{}{}, resp.json, "Expected JSON array response, got %v", resp.json)
```
Comment (eschwartz) [inline tests/acceptance/api_test.go]: Previous, tests would panic if we got an error response instead of a JSON list. Add a check here to fail more gracefully.

Comment (kddejong) [reply tests/acceptance/api_test.go]: Thanks.  This is one of the things that was annoying when I was discussing the different response structures.  If you expect a list but get an error you have to adjust how you parse the output.  This should help.

File: modules/fixtures/policies/principal_policy.tmpl [hunk 10]
```diff
@@ -110,6 +110,7 @@
         "elastictranscoder:*",
         "es:*",
         "events:*",
+        "execute-api:*",
```
Comment (kddejong) [inline modules/fixtures/policies/principal_policy.tmpl]: Should we include this in the doc change to the SCP as well?

**Comment by eschwartz** [comment]
> Minus the change to the SCP to include execute-api this looks good.

@kddejong I'm on it
